services:
  idrive:
    build: ./idrive/build/
    image: snorre0815/idrive-docker:latest
    container_name: idrive
    volumes:
      - idrive:/opt/IDriveForLinux/idriveIt
      - /path/to/backup:/source/1:ro
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC

volumes:
  idrive:

