all:
  hosts:
    k3s-master-0:
    k3s-master-1:
    k3s-master-2:
    k3s-worker-0:
    k3s-worker-1:
    k3s-worker-2:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3
  children:
    kube_control_plane:
      hosts:
        k3s-master-0:
        k3s-master-1:
        k3s-master-2:
    kube_node:
      hosts:
        k3s-worker-0:
        k3s-worker-1:
        k3s-worker-2:
    etcd:
      hosts:
        k3s-master-0:
        k3s-master-1:
        k3s-master-2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
